# -*- coding: utf-8 -*-
"""problem2-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wCRFtvsrV3dK-nWGm7ZgLqyR6qlYwNgQ
"""

import numpy as np
import pandas as pd
import io
from google.colab import files
file_uploaded = files.upload()

#pd.read_csv('2019_kbo_for_kaggle_v2.csv') : colab 오류로 file 업로드를 통해 전달하겠습니다.
kbo = pd.read_csv(io.BytesIO(file_uploaded['2019_kbo_for_kaggle_v2.csv']))

kbo2015_2018 = pd.DataFrame()
kbo2015_2018 = kbo[kbo['year'] >= 2015]
kbo2015_2018 = kbo2015_2018[kbo2015_2018['year'] <= 2018]

problem1_H = kbo2015_2018.nlargest(10,'H')
problem1_H #first problem

problem1_avg = kbo2015_2018.nlargest(10,'avg')
problem1_avg

problem1_OBP = kbo2015_2018.nlargest(10,'OBP')
problem1_OBP

kbo2018 = kbo[kbo['year'] == 2018]
kbo2018_1 = kbo2018[kbo2018['tp'] == '포수']
kbo2018_1 = kbo2018_1.nlargest(1,'war')
kbo2018_2 = kbo2018[kbo2018['tp'] == '1루수']
kbo2018_2 = kbo2018_2.nlargest(1,'war')
kbo2018_3 = kbo2018[kbo2018['tp'] == '2루수']
kbo2018_3 = kbo2018_3.nlargest(1,'war')
kbo2018_4 = kbo2018[kbo2018['tp'] == '3루수']
kbo2018_4 = kbo2018_4.nlargest(1,'war')
kbo2018_5 = kbo2018[kbo2018['tp'] == '유격수']
kbo2018_5 = kbo2018_5.nlargest(1,'war')
kbo2018_6 = kbo2018[kbo2018['tp'] == '좌익수']
kbo2018_6 = kbo2018_6.nlargest(1,'war')
kbo2018_7 = kbo2018[kbo2018['tp'] == '중견수']
kbo2018_7 = kbo2018_7.nlargest(1,'war')
kbo2018_8 = kbo2018[kbo2018['tp'] == '우익수']
kbo2018_8 = kbo2018_8.nlargest(1,'war')

problem2 = pd.DataFrame()
problem2 = pd.concat([kbo2018_1,kbo2018_2,kbo2018_3,kbo2018_4,kbo2018_5,kbo2018_6,kbo2018_7,kbo2018_8])
problem2 #second problem

kbo_problem3 = kbo.drop(['age','G','PA','AB','R','2B','3B','TB','CS','BB','HBP','GB','SO','GDP','BU','fly','year','year_born','hand2','cp','tp','1B','FBP','OPS','p_year','YAB','YOPS'],axis=1)
problem3 = kbo_problem3.corrwith(kbo_problem3.salary)
problem3 #third problem(RBI is best)